---
- hosts: all
  become: yes
  vars_files: secret.yml
  tasks:
   - name: yum-update
     yum:
      update_cache: yes   
   - name: Installing Docker Prerequisite packages
     yum:
      name: "{{ item }}"
      state: latest
     with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
   - name: "Configuring docker-ce repo"
     get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0644
   - name: " Installing Docker latest version"
     yum:
      name: docker-ce
      state: present
   - name: " Starting and Enabling Docker service"
     service:
      name: docker
      state: started
      enabled: yes
   - name: Create new directory
     become_user: centos
     file:
      path: /home/centos/target
      state: directory
   - name: Copy the source code to hosts
     copy: src=./{{ item }} dest=/home/centos/target/
     become_user: centos
     with_items:
        - app
        - migrations
        - flasky.py
        - config.py
        - boot.sh
        - data-dev.sqlite
        - Dockerfile
        - requirements
   - name: Set the executable permission
     command: chmod +x /home/centos/target/boot.sh  
   - name: Build Docker Image
     command: chdir=/home/centos/target/ docker build . -t mediaapp
   - name: Stop docker container
     command: docker stop mediaapp_container
   - name: Remove docker container
     command: docker system prune -f
   - name: Run Docker Container
     command: chdir=/home/centos/target/ docker run --name=mediaapp_container -itd -e SECRET_KEY="{{ SECRET_KEY }}" -p 80:5000 mediaapp
